local _, ns = ...
ns.Lru = {
    ["Show enchants text"]          = "Показывать чары",
    ["Show gems text"]              = "Показывать камни",
    ["Show quality borders"]        = "Показывать рамки качества",
    ["Lock frame"]                  = "Закрепить окно",
    ["Unlock frame"]                = "Открепить окно",
    ["Scale"]                       = "Масштаб",
    ["Icon spacing"]                = "Интервал иконок",
    ["Available commands:"]         = "Доступные команды:",
    ["Reset configuration"]         = "Сбросить настройки",
    ["Configuration reset."]        = "Настройки сброшены.",
    ["Change scale (e.g. 1.2)"]    = "Изменить масштаб (например 1.2)",
    ["Change icon spacing"]         = "Изменить интервал иконок",
    ["Toggle quality borders"]      = "Переключить рамки качества",
    ["Toggle enchants text"]        = "Переключить текст чар",
    ["Toggle gems text"]            = "Переключить текст камней",
    ["Usage:"]                      = "Использование:",
    ["Borders"]                     = "Рамки",
    ["Enchants"]                    = "Чары",
    ["Gems"]                        = "Камни",
    ["Unknown command."]            = "Неизвестная команда.",
    ["Frame locked."]               = "Окно закреплено.",
    ["Frame unlocked. (Shift+Alt+click to move)"] = "Окно откреплено (Shift+Alt+клик для перемещения).",
    ["Configure how EquippedWeapons displays weapon icons, enchants, and gems."] = "Настройка отображения значков оружия, чар и камней в EquippedWeapons.",
    -- Layout & Text
    ["Show text horizontally"]      = "Показывать текст горизонтально",
    ["Vertical icon layout"]        = "Вертикальное расположение иконок",
    ["Grow upwards"]                = "Расширять вверх",
    ["Abbreviate text (short mode)"] = "Сокращать текст (краткий режим)",
    -- Weapon slots
    ["Main Hand"]                   = "Основная рука",
    ["Off Hand"]                    = "Вторая рука",
    ["Ranged / Relic"]              = "Дальний бой / Реликвия",
    -- Profile & Text size
    ["Per-character settings"]      = "Настройки персонажа",
    ["Hide chat messages"] = "Скрыть сообщения чата",
    ["Hide slot labels"]            = "Скрыть метки слотов",
    ["Text size"]                   = "Размер текста",
}
