local _, ns = ...
ns.Len = {
    ["Show enchants text"]          = "Show enchants text",
    ["Show gems text"]              = "Show gems text",
    ["Show quality borders"]        = "Show quality borders",
    ["Lock frame"]                  = "Lock frame",
    ["Unlock frame"]                = "Unlock frame",
    ["Scale"]                       = "Scale",
    ["Icon spacing"]                = "Icon spacing",
    ["Available commands:"]         = "Available commands:",
    ["Reset configuration"]         = "Reset configuration",
    ["Configuration reset."]        = "Configuration reset.",
    ["Change scale (e.g. 1.2)"]    = "Change scale (e.g. 1.2)",
    ["Change icon spacing"]         = "Change icon spacing",
    ["Toggle quality borders"]      = "Toggle quality borders",
    ["Toggle enchants text"]        = "Toggle enchants text",
    ["Toggle gems text"]            = "Toggle gems text",
    ["Usage:"]                      = "Usage:",
    ["Borders"]                     = "Borders",
    ["Enchants"]                    = "Enchants",
    ["Gems"]                        = "Gems",
    ["Unknown command."]            = "Unknown command.",
    ["Frame locked."]               = "Frame locked.",
    ["Frame unlocked. (Shift+Alt+click to move)"] = "Frame unlocked (Shift+Alt+click to move).",
    ["Configure how EquippedWeapons displays weapon icons, enchants, and gems."] = "Configure how EquippedWeapons displays weapon icons, enchants, and gems.",
    -- Layout & Text
    ["Show text horizontally"]      = "Show text horizontally",
    ["Vertical icon layout"]        = "Vertical icon layout",
    ["Grow upwards"]                = "Grow upwards",
    ["Abbreviate text (short mode)"] = "Abbreviate text (short mode)",
    -- Weapon slots
    ["Main Hand"]                   = "Main Hand",
    ["Off Hand"]                    = "Off Hand",
    ["Ranged / Relic"]              = "Ranged / Relic",
    -- Profile & Text size
    ["Per-character settings"]      = "Per-character settings",
    ["Hide slot labels"]            = "Hide slot labels",
    ["Show full poison name"]       = "Show full poison name",
    ["Show poison text"]            = "Show poison text",
    ["Show poison icon"]            = "Show poison icon",
    ["Text size"]                   = "Text size",
}