local _, ns = ...
ns.Les = {
    ["Show enchants text"]          = "Mostrar encantamientos",
    ["Show gems text"]              = "Mostrar gemas",
    ["Show quality borders"]        = "Mostrar bordes de rareza",
    ["Lock frame"]                  = "Bloquear marco",
    ["Unlock frame"]                = "Desbloquear marco",
    ["Scale"]                       = "Escala",
    ["Icon spacing"]                = "Separación de iconos",
    ["Available commands:"]         = "Comandos disponibles:",
    ["Reset configuration"]         = "Reinicia configuración",
    ["Configuration reset."]        = "Configuración reiniciada.",
    ["Change scale (e.g. 1.2)"]    = "Cambia escala (ej: 1.2)",
    ["Change icon spacing"]         = "Cambia separación de iconos",
    ["Toggle quality borders"]      = "Alterna bordes de calidad",
    ["Toggle enchants text"]        = "Alterna texto de encantamientos",
    ["Toggle gems text"]            = "Alterna texto de gemas",
    ["Usage:"]                      = "Uso:",
    ["Borders"]                     = "Bordes",
    ["Enchants"]                    = "Encantamientos",
    ["Gems"]                        = "Gemas",
    ["Unknown command."]            = "Comando desconocido.",
    ["Frame locked."]               = "Marco bloqueado.",
    ["Frame unlocked. (Shift+Alt+click to move)"] = "Marco desbloqueado (Shift+Alt+clic para mover).",
    ["Configure how EquippedWeapons displays weapon icons, enchants, and gems."] = "Configura cómo EquippedWeapons muestra iconos, encantamientos y gemas.",
    -- Layout & Text
    ["Show text horizontally"]      = "Mostrar texto horizontal",
    ["Vertical icon layout"]        = "Iconos en vertical",
    ["Grow upwards"]                = "Crecer hacia arriba",
    ["Abbreviate text (short mode)"] = "Abreviar texto (modo corto)",
    -- Weapon slots
    ["Main Hand"]                   = "Mano principal",
    ["Off Hand"]                    = "Mano secundaria",
    ["Ranged / Relic"]              = "A distancia / Reliquia",
    -- Profile & Text size
    ["Per-character settings"]      = "Ajustes por personaje",
    ["Hide chat messages"] = "Ocultar mensajes del chat",
    ["Hide slot labels"]            = "Ocultar etiquetas de ranura",
    ["Show full poison name"]       = "Mostrar nombre completo del veneno",
    ["Text size"]                   = "Tamaño de texto",
}