local _, ns = ...
ns.Lde = {
    ["Show enchants text"]          = "Verzauberungen anzeigen",
    ["Show gems text"]              = "Edelsteine anzeigen",
    ["Show quality borders"]        = "Qualitätsrahmen anzeigen",
    ["Lock frame"]                  = "Fenster sperren",
    ["Unlock frame"]                = "Fenster entsperren",
    ["Scale"]                       = "Skalierung",
    ["Icon spacing"]                = "Symbolabstand",
    ["Available commands:"]         = "Verfügbare Befehle:",
    ["Reset configuration"]         = "Konfiguration zurücksetzen",
    ["Configuration reset."]        = "Konfiguration zurückgesetzt.",
    ["Change scale (e.g. 1.2)"]    = "Skalierung ändern (z. B. 1.2)",
    ["Change icon spacing"]         = "Symbolabstand ändern",
    ["Toggle quality borders"]      = "Qualitätsrahmen umschalten",
    ["Toggle enchants text"]        = "Verzauberungstext umschalten",
    ["Toggle gems text"]            = "Edelsteintext umschalten",
    ["Usage:"]                      = "Verwendung:",
    ["Borders"]                     = "Rahmen",
    ["Enchants"]                    = "Verzauberungen",
    ["Gems"]                        = "Edelsteine",
    ["Unknown command."]            = "Unbekannter Befehl.",
    ["Frame locked."]               = "Fenster gesperrt.",
    ["Frame unlocked. (Shift+Alt+click to move)"] = "Fenster entsperrt (Shift+Alt+Klick zum Bewegen).",
    ["Configure how EquippedWeapons displays weapon icons, enchants, and gems."] = "Konfiguriere, wie EquippedWeapons Waffensymbole, Verzauberungen und Edelsteine anzeigt.",
    -- Layout & Text
    ["Show text horizontally"]      = "Text horizontal anzeigen",
    ["Vertical icon layout"]        = "Symbole vertikal anordnen",
    ["Grow upwards"]                = "Nach oben wachsen",
    ["Abbreviate text (short mode)"] = "Text abkürzen (Kurzformat)",
    -- Weapon slots
    ["Main Hand"]                   = "Haupthand",
    ["Off Hand"]                    = "Nebenhand",
    ["Ranged / Relic"]              = "Fernkampf / Relikt",
    -- Profile & Text size
    ["Per-character settings"]      = "Charakterspezifische Einstellungen",
    ["Hide slot labels"]            = "Slot-Bezeichnungen ausblenden",
    ["Show full poison name"]       = "Vollständigen Giftnamen anzeigen",
    ["Show poison text"]            = "Gifttext anzeigen",
    ["Show poison icon"]            = "Giftsymbol anzeigen",
    ["Text size"]                   = "Textgröße",
}
