local _, ns = ...
ns.Lfr = {
    ["Show enchants text"]          = "Afficher les enchantements",
    ["Show gems text"]              = "Afficher les gemmes",
    ["Show quality borders"]        = "Afficher les bordures de qualité",
    ["Lock frame"]                  = "Verrouiller la fenêtre",
    ["Unlock frame"]                = "Déverrouiller la fenêtre",
    ["Scale"]                       = "Échelle",
    ["Icon spacing"]                = "Espacement des icônes",
    ["Available commands:"]         = "Commandes disponibles:",
    ["Reset configuration"]         = "Réinitialiser la configuration",
    ["Configuration reset."]        = "Configuration réinitialisée.",
    ["Change scale (e.g. 1.2)"]    = "Changer l'échelle (ex: 1.2)",
    ["Change icon spacing"]         = "Changer l'espacement des icônes",
    ["Toggle quality borders"]      = "Activer/désactiver les bordures de qualité",
    ["Toggle enchants text"]        = "Activer/désactiver le texte des enchantements",
    ["Toggle gems text"]            = "Activer/désactiver le texte des gemmes",
    ["Usage:"]                      = "Utilisation:",
    ["Borders"]                     = "Bordures",
    ["Enchants"]                    = "Enchantements",
    ["Gems"]                        = "Gemmes",
    ["Unknown command."]            = "Commande inconnue.",
    ["Frame locked."]               = "Fenêtre verrouillée.",
    ["Frame unlocked. (Shift+Alt+click to move)"] = "Fenêtre déverrouillée (Shift+Alt+Clic pour déplacer).",
    ["Configure how EquippedWeapons displays weapon icons, enchants, and gems."] = "Configurer comment EquippedWeapons affiche les icônes, enchantements et gemmes.",
    -- Layout & Text
    ["Show text horizontally"]      = "Afficher le texte horizontalement",
    ["Vertical icon layout"]        = "Disposition verticale des icônes",
    ["Grow upwards"]                = "Développer vers le haut",
    ["Abbreviate text (short mode)"] = "Abréger le texte (mode court)",
    -- Weapon slots
    ["Main Hand"]                   = "Main principale",
    ["Off Hand"]                    = "Main secondaire",
    ["Ranged / Relic"]              = "Distance / Relique",
    -- Profile & Text size
    ["Per-character settings"]      = "Paramètres par personnage",
    ["Hide slot labels"]            = "Masquer les étiquettes d'emplacement",
    ["Show full poison name"]       = "Afficher le nom complet du poison",
    ["Show poison text"]            = "Afficher le texte du poison",
    ["Show poison icon"]            = "Afficher l'icône du poison",
    ["Text size"]                   = "Taille du texte",
}
